# This property describes the priority order of cards, this order changes with the type of card game you want to play.
card:
  color-orders:
    DIAMONDS: 1
    HEARTS: 2
    SPADES: 3
    CLUB: 4
  value-orders:
    AS: 1
    V2: 2
    V3: 3
    V4: 4
    V5: 5
    V6: 6
    V7: 7
    V8: 8
    V9: 9
    V10: 10
    JACK: 11
    QUEEN: 12
    KING: 13